# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  timeout: 240s
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - gocognit
    - revive
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - wsl_v5
    - nilnesserr
    - nakedret

  settings:
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: get-return
        - name: early-return
        - name: identical-branches
        - name: defer
          arguments:
            - - loop
              - method-call
              - return
        - name: string-of-int
        - name: waitgroup-by-value
        - name: range-val-address
        - name: argument-limit
          arguments:
            - 10
        - name: atomic
        - name: bool-literal-in-expr
        - name: deep-exit
        - name: function-result-limit
          arguments:
            - 5
        - name: modifies-value-receiver
        - name: unnecessary-stmt
    gocyclo:
      min-complexity: 9
    gocognit:
      min-complexity: 10
    gocritic:
      enable-all: true
      disabled-checks:
        - ifElseChain
        - unnecessaryBlock
        - sprintfQuotedString
        - deferUnlambda
        - paramTypeCombine
        - builtinShadow
        - octalLiteral
        - rangeValCopy
        - nestingReduce
        - httpNoBody
        - regexpSimplify
        - externalErrorReassign
        - hugeParam
        - importShadow
        - unnamedResult
        - filepathJoin
        - commentedOutCode
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - err
      disable:
        - assign
        - decl
    gosec:
      excludes:
        - "G115"
        - "G602"
    staticcheck:
      checks:
        - all
        - -QF1008
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
        - nilness

  exclusions:
    generated: disable
    rules:
      - path: autogenerated\.go$
        linters:
          - gocyclo
          - gocognit

      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - staticcheck
          - wsl
          - wsl_v5
