/*
Package server provides an HTTP-compatible DynamoDB mock backed by the
minidyn core. It is designed to be used with httptest.NewServer and real AWS
SDK clients so you can exercise application code without swapping clients.

Key features:
  - DynamoDB JSON API: Supports CreateTable/DescribeTable/UpdateTable/DeleteTable,
    PutItem/GetItem/UpdateItem/DeleteItem, Query, Scan, and BatchWriteItem.
  - AWS SDK v2 friendly: Use the standard dynamodb.Client with a custom endpoint
    resolver pointing at the httptest server.
  - Generated request shapes: Input structs in requests.go are generated by
    tools/generate_requests to allow JSON unmarshalling without the SDK’s
    AttributeValue interfaces.
  - Failure emulation: EmulateFailure lets you force InternalServerError
    responses to test retry/error handling paths.

Typical usage:

	srv := httptest.NewServer(server.NewServer())
	defer srv.Close()

	cfg, _ := config.LoadDefaultConfig(ctx,
	    config.WithRegion("us-east-1"),
	    config.WithEndpointResolverWithOptions(
	        dynamodb.EndpointResolverFromURL(srv.URL),
	    ),
	)
	ddb := dynamodb.NewFromConfig(cfg)

	// Use ddb as usual (CreateTable, PutItem, Query, etc.)

For developers:
  - Regenerate request shapes when DynamoDB inputs change:
    go run ./tools/generate_requests
    This rewrites server/requests.go based on AWS SDK v2 DynamoDB inputs,
    replacing AttributeValue interfaces with concrete JSON-friendly types.
*/
package server
