// Code generated by scripts/generate_requests.go; DO NOT EDIT.

// Package server exposes request shapes mirrored from DynamoDB inputs.
package server

import (
	ddbtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

type AttributeValueUpdate struct {
	Action ddbtypes.AttributeAction `json:"Action,omitempty"`
	Value  *AttributeValue          `json:"Value,omitempty"`
}

type BatchGetItemInput struct {
	RequestItems           map[string]KeysAndAttributes    `json:"RequestItems,omitempty"`
	ReturnConsumedCapacity ddbtypes.ReturnConsumedCapacity `json:"ReturnConsumedCapacity,omitempty"`
}

type BatchWriteItemInput struct {
	RequestItems                map[string][]WriteRequest            `json:"RequestItems,omitempty"`
	ReturnConsumedCapacity      ddbtypes.ReturnConsumedCapacity      `json:"ReturnConsumedCapacity,omitempty"`
	ReturnItemCollectionMetrics ddbtypes.ReturnItemCollectionMetrics `json:"ReturnItemCollectionMetrics,omitempty"`
}

type Condition struct {
	ComparisonOperator ddbtypes.ComparisonOperator `json:"ComparisonOperator,omitempty"`
	AttributeValueList []*AttributeValue           `json:"AttributeValueList,omitempty"`
}

type ConditionCheck struct {
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	Key                                 map[string]*AttributeValue                   `json:"Key,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type CreateTableInput struct {
	AttributeDefinitions      []ddbtypes.AttributeDefinition  `json:"AttributeDefinitions,omitempty"`
	KeySchema                 []ddbtypes.KeySchemaElement     `json:"KeySchema,omitempty"`
	TableName                 *string                         `json:"TableName,omitempty"`
	BillingMode               ddbtypes.BillingMode            `json:"BillingMode,omitempty"`
	DeletionProtectionEnabled *bool                           `json:"DeletionProtectionEnabled,omitempty"`
	GlobalSecondaryIndexes    []ddbtypes.GlobalSecondaryIndex `json:"GlobalSecondaryIndexes,omitempty"`
	LocalSecondaryIndexes     []ddbtypes.LocalSecondaryIndex  `json:"LocalSecondaryIndexes,omitempty"`
	ProvisionedThroughput     *ddbtypes.ProvisionedThroughput `json:"ProvisionedThroughput,omitempty"`
	SSESpecification          *ddbtypes.SSESpecification      `json:"SSESpecification,omitempty"`
	StreamSpecification       *ddbtypes.StreamSpecification   `json:"StreamSpecification,omitempty"`
	TableClass                ddbtypes.TableClass             `json:"TableClass,omitempty"`
	Tags                      []ddbtypes.Tag                  `json:"Tags,omitempty"`
}

type Delete struct {
	Key                                 map[string]*AttributeValue                   `json:"Key,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type DeleteItemInput struct {
	Key                                 map[string]*AttributeValue                   `json:"Key,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ConditionalOperator                 ddbtypes.ConditionalOperator                 `json:"ConditionalOperator,omitempty"`
	Expected                            map[string]ExpectedAttributeValue            `json:"Expected,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnConsumedCapacity              ddbtypes.ReturnConsumedCapacity              `json:"ReturnConsumedCapacity,omitempty"`
	ReturnItemCollectionMetrics         ddbtypes.ReturnItemCollectionMetrics         `json:"ReturnItemCollectionMetrics,omitempty"`
	ReturnValues                        ddbtypes.ReturnValue                         `json:"ReturnValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type DeleteRequest struct {
	Key map[string]*AttributeValue `json:"Key,omitempty"`
}

type DeleteTableInput struct {
	TableName *string `json:"TableName,omitempty"`
}

type DescribeTableInput struct {
	TableName *string `json:"TableName,omitempty"`
}

type ExpectedAttributeValue struct {
	AttributeValueList []*AttributeValue           `json:"AttributeValueList,omitempty"`
	ComparisonOperator ddbtypes.ComparisonOperator `json:"ComparisonOperator,omitempty"`
	Exists             *bool                       `json:"Exists,omitempty"`
	Value              *AttributeValue             `json:"Value,omitempty"`
}

type GetItemInput struct {
	Key                      map[string]*AttributeValue      `json:"Key,omitempty"`
	TableName                *string                         `json:"TableName,omitempty"`
	AttributesToGet          []string                        `json:"AttributesToGet,omitempty"`
	ConsistentRead           *bool                           `json:"ConsistentRead,omitempty"`
	ExpressionAttributeNames map[string]string               `json:"ExpressionAttributeNames,omitempty"`
	ProjectionExpression     *string                         `json:"ProjectionExpression,omitempty"`
	ReturnConsumedCapacity   ddbtypes.ReturnConsumedCapacity `json:"ReturnConsumedCapacity,omitempty"`
}

type KeysAndAttributes struct {
	Keys                     []map[string]*AttributeValue `json:"Keys,omitempty"`
	AttributesToGet          []string                     `json:"AttributesToGet,omitempty"`
	ConsistentRead           *bool                        `json:"ConsistentRead,omitempty"`
	ExpressionAttributeNames map[string]string            `json:"ExpressionAttributeNames,omitempty"`
	ProjectionExpression     *string                      `json:"ProjectionExpression,omitempty"`
}

type Put struct {
	Item                                map[string]*AttributeValue                   `json:"Item,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type PutItemInput struct {
	Item                                map[string]*AttributeValue                   `json:"Item,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ConditionalOperator                 ddbtypes.ConditionalOperator                 `json:"ConditionalOperator,omitempty"`
	Expected                            map[string]ExpectedAttributeValue            `json:"Expected,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnConsumedCapacity              ddbtypes.ReturnConsumedCapacity              `json:"ReturnConsumedCapacity,omitempty"`
	ReturnItemCollectionMetrics         ddbtypes.ReturnItemCollectionMetrics         `json:"ReturnItemCollectionMetrics,omitempty"`
	ReturnValues                        ddbtypes.ReturnValue                         `json:"ReturnValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type PutRequest struct {
	Item map[string]*AttributeValue `json:"Item,omitempty"`
}

type QueryInput struct {
	TableName                 *string                         `json:"TableName,omitempty"`
	AttributesToGet           []string                        `json:"AttributesToGet,omitempty"`
	ConditionalOperator       ddbtypes.ConditionalOperator    `json:"ConditionalOperator,omitempty"`
	ConsistentRead            *bool                           `json:"ConsistentRead,omitempty"`
	ExclusiveStartKey         map[string]*AttributeValue      `json:"ExclusiveStartKey,omitempty"`
	ExpressionAttributeNames  map[string]string               `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues map[string]*AttributeValue      `json:"ExpressionAttributeValues,omitempty"`
	FilterExpression          *string                         `json:"FilterExpression,omitempty"`
	IndexName                 *string                         `json:"IndexName,omitempty"`
	KeyConditionExpression    *string                         `json:"KeyConditionExpression,omitempty"`
	KeyConditions             map[string]Condition            `json:"KeyConditions,omitempty"`
	Limit                     *int32                          `json:"Limit,omitempty"`
	ProjectionExpression      *string                         `json:"ProjectionExpression,omitempty"`
	QueryFilter               map[string]Condition            `json:"QueryFilter,omitempty"`
	ReturnConsumedCapacity    ddbtypes.ReturnConsumedCapacity `json:"ReturnConsumedCapacity,omitempty"`
	ScanIndexForward          *bool                           `json:"ScanIndexForward,omitempty"`
	Select                    ddbtypes.Select                 `json:"Select,omitempty"`
}

type ScanInput struct {
	TableName                 *string                         `json:"TableName,omitempty"`
	AttributesToGet           []string                        `json:"AttributesToGet,omitempty"`
	ConditionalOperator       ddbtypes.ConditionalOperator    `json:"ConditionalOperator,omitempty"`
	ConsistentRead            *bool                           `json:"ConsistentRead,omitempty"`
	ExclusiveStartKey         map[string]*AttributeValue      `json:"ExclusiveStartKey,omitempty"`
	ExpressionAttributeNames  map[string]string               `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues map[string]*AttributeValue      `json:"ExpressionAttributeValues,omitempty"`
	FilterExpression          *string                         `json:"FilterExpression,omitempty"`
	IndexName                 *string                         `json:"IndexName,omitempty"`
	Limit                     *int32                          `json:"Limit,omitempty"`
	ProjectionExpression      *string                         `json:"ProjectionExpression,omitempty"`
	ReturnConsumedCapacity    ddbtypes.ReturnConsumedCapacity `json:"ReturnConsumedCapacity,omitempty"`
	ScanFilter                map[string]Condition            `json:"ScanFilter,omitempty"`
	Segment                   *int32                          `json:"Segment,omitempty"`
	Select                    ddbtypes.Select                 `json:"Select,omitempty"`
	TotalSegments             *int32                          `json:"TotalSegments,omitempty"`
}

type TransactWriteItem struct {
	ConditionCheck *ConditionCheck `json:"ConditionCheck,omitempty"`
	Delete         *Delete         `json:"Delete,omitempty"`
	Put            *Put            `json:"Put,omitempty"`
	Update         *Update         `json:"Update,omitempty"`
}

type TransactWriteItemsInput struct {
	TransactItems               []TransactWriteItem                  `json:"TransactItems,omitempty"`
	ClientRequestToken          *string                              `json:"ClientRequestToken,omitempty"`
	ReturnConsumedCapacity      ddbtypes.ReturnConsumedCapacity      `json:"ReturnConsumedCapacity,omitempty"`
	ReturnItemCollectionMetrics ddbtypes.ReturnItemCollectionMetrics `json:"ReturnItemCollectionMetrics,omitempty"`
}

type Update struct {
	Key                                 map[string]*AttributeValue                   `json:"Key,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	UpdateExpression                    *string                                      `json:"UpdateExpression,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
}

type UpdateItemInput struct {
	Key                                 map[string]*AttributeValue                   `json:"Key,omitempty"`
	TableName                           *string                                      `json:"TableName,omitempty"`
	AttributeUpdates                    map[string]AttributeValueUpdate              `json:"AttributeUpdates,omitempty"`
	ConditionExpression                 *string                                      `json:"ConditionExpression,omitempty"`
	ConditionalOperator                 ddbtypes.ConditionalOperator                 `json:"ConditionalOperator,omitempty"`
	Expected                            map[string]ExpectedAttributeValue            `json:"Expected,omitempty"`
	ExpressionAttributeNames            map[string]string                            `json:"ExpressionAttributeNames,omitempty"`
	ExpressionAttributeValues           map[string]*AttributeValue                   `json:"ExpressionAttributeValues,omitempty"`
	ReturnConsumedCapacity              ddbtypes.ReturnConsumedCapacity              `json:"ReturnConsumedCapacity,omitempty"`
	ReturnItemCollectionMetrics         ddbtypes.ReturnItemCollectionMetrics         `json:"ReturnItemCollectionMetrics,omitempty"`
	ReturnValues                        ddbtypes.ReturnValue                         `json:"ReturnValues,omitempty"`
	ReturnValuesOnConditionCheckFailure ddbtypes.ReturnValuesOnConditionCheckFailure `json:"ReturnValuesOnConditionCheckFailure,omitempty"`
	UpdateExpression                    *string                                      `json:"UpdateExpression,omitempty"`
}

type UpdateTableInput struct {
	TableName                   *string                               `json:"TableName,omitempty"`
	AttributeDefinitions        []ddbtypes.AttributeDefinition        `json:"AttributeDefinitions,omitempty"`
	BillingMode                 ddbtypes.BillingMode                  `json:"BillingMode,omitempty"`
	DeletionProtectionEnabled   *bool                                 `json:"DeletionProtectionEnabled,omitempty"`
	GlobalSecondaryIndexUpdates []ddbtypes.GlobalSecondaryIndexUpdate `json:"GlobalSecondaryIndexUpdates,omitempty"`
	ProvisionedThroughput       *ddbtypes.ProvisionedThroughput       `json:"ProvisionedThroughput,omitempty"`
	ReplicaUpdates              []ddbtypes.ReplicationGroupUpdate     `json:"ReplicaUpdates,omitempty"`
	SSESpecification            *ddbtypes.SSESpecification            `json:"SSESpecification,omitempty"`
	StreamSpecification         *ddbtypes.StreamSpecification         `json:"StreamSpecification,omitempty"`
	TableClass                  ddbtypes.TableClass                   `json:"TableClass,omitempty"`
}

type WriteRequest struct {
	DeleteRequest *DeleteRequest `json:"DeleteRequest,omitempty"`
	PutRequest    *PutRequest    `json:"PutRequest,omitempty"`
}
