package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunGeneratesRequestsFile(t *testing.T) {
	tmp := t.TempDir()
	out := filepath.Join(tmp, "requests.go")

	if err := run(out); err != nil {
		t.Fatalf("run() error = %v", err)
	}

	data, err := os.ReadFile(out) //nolint:gosec // test reads known temp file
	if err != nil {
		t.Fatalf("read output: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Code generated by tools/generate_requests") {
		t.Fatalf("missing header in output")
	}
	if !strings.Contains(content, "type PutItemInput") {
		t.Fatalf("missing PutItemInput in output")
	}
	if !strings.Contains(content, "*AttributeValue") {
		t.Fatalf("expected concrete AttributeValue usage")
	}
}
